services:

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: devteds@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: devteds      
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres
    restart: always          
    environment: 
      POSTGRES_USER: devtedsuser
      POSTGRES_PASSWORD: devtedspass
      POSTGRES_DB: demodb
    ports:
      - 5432:5432
    volumes:                 
      - pg-data:/var/lib/postgresql/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../otel-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8889:8889"  
    depends_on:
      - db

volumes:
  pgadmin-data:
  pg-data: